### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by juhha1** [nv-tlabs/XCube#25]
Thanks for providing the code for generating ShapeNet dataset. It is very helpful.

In there, I have few questions regarding data processing.
1.  The format (file extension) of the dataset. I think the ShapeNet data generation code in this repo takes ".ply" files for ShapeNet dataset. But when I downloaded the raw dataset, it is either ".obj" or ".off" format. Did you perform any processing to generate ".ply"?
2. Is the input data only contain the "outer surface" of the mesh? When I investigate the output of XCube (pretrained models for ShapeNet objects), it contains 1 mesh without any "inner object". For example, the raw mesh from ShapeNet Car has multiple objects including "inner objects" like car seats, handles, and etc. as well. But I only see one outer surface of the car in generated mesh. Did the input to train this model only contain the outer surface without inner objects?

Thanks for reading my comments here!

**Comment by xrenaa** [comment]
Hi, thanks for your interest.

1. For the ply files, we do an additonal processing to convert the trigangle mesh to Watertight Manifold for applying SDF extraction. XCube itself do not require the mesh to be watertight. 

2. Same with above, XCube do not constrain the mesh to be only outer surface. For ShapeNet, we want to extract SDF and thus we do an additonal processing to convert the trigangle mesh to Watertight Manifold. For Objaverse, the object contains inner surface, since we only extract UDF.

**Comment by juhha1** [comment]
Can you tell me how this pre-processing (triangle mesh to Watertight Manifold) is done? Was some software used? Or any Python script for this?

Thanks!

**Comment by xrenaa** [comment]
We use something similar to https://github.com/davidstutz/mesh-fusion and https://github.com/autonomousvision/occupancy_networks?tab=readme-ov-file#building-the-dataset

**Comment by juhha1** [comment]
Thank you very much!
