### ISSUE TITLE
Coordinates space range question?

### ISSUE THREAD

**Issue by krNeko9t** [nv-tlabs/XCube#31]
Such as checkpoint trained on ShapeNet, i noticed that the (dense) voxel size is 0.01, but the voxel index range(grid resolution) is -128 to 128, so is that means the (output) mesh vertex position is limited to -1.28 to 1.28?
I used the generated mesh to be forward to VAE, and find that *128/100 is not needed (in datagen/shapenet_example.py)

**Comment by xrenaa** [comment]
Hi, for the "* 128 / 100", it is because when we generate the voxel from mesh, it is of voxel size 1/ 128, so we rescale it to 0.01 by *128 / 100.

**Comment by krNeko9t** [comment]
> Hi, for the "* 128 / 100", it is because when we generate the voxel from mesh, it is of voxel size 1/ 128, so we rescale it to 0.01 by *128 / 100.

thank you for your answer! If I understand correctly, in fvdb, the world space is consist, and the ijk index space is related to voxel size. So to limit the ijk range to (-128,128) with voxel size 0.01, the xyz coord is rescaled to 0.01 by *128 / 100 (if the xyz coord range in (-1,1)?). 
But i used the sampled mesh ( from sample_shapenet.py) to go through the VAE again, and found that the rescale operation is no needed, so i guess the sampled mesh's coord range in (-1.28,1.28)?
And i would like to know anything special for the voxel size to be set to 0.01? Isn't it be 1/128 more convenient?

**Comment by xrenaa** [comment]
Ah I kind of getting your question. 
Actually, FVDB Network is not sensitive to voxel size since it is only relied on ijk which is coverted from the world coord using voxel size. 
Here why we use 0.01 is just because we previously wanted to aligned our format to Conv-Onet dataset format. It doesn't matter to use 0.01 or 1/128 for actual usage. 
Just keep in mind if you remove the *128 / 100 term, it is better to change the voxel size to 1/128 accordingly.

**Comment by fxlong** [comment]
@krNeko9t hi,  Is it correct to send the generated result to vae again?
